services:
  - type: web
    name: parcial-django
    env: python
    region: oregon
    buildCommand: "./.venv/Scripts/pip install -r requirements.txt || pip install -r requirements.txt"
    startCommand: "gunicorn parcial.wsgi"
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: parcial.settings
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ""
      - key: DATABASE_URL
        fromDatabase:
          name: parcial-db
          property: connectionString
    disk:
      name: media
      mountPath: /opt/render/project/src/media
databases:
  - name: parcial-db
    databaseName: parcial
    user: parcial_user
