services:
  - type: web
    name: parcial20
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn parcial20.wsgi --bind 0.0.0.0:$PORT --log-file -"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: parcial20.settings
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ""
      - key: EMAIL_HOST_USER
        value: "test@example.com"
      - key: DATABASE_URL
        fromDatabase:
          name: parcial20-db
          property: connectionString
    disk:
      name: media
      mountPath: /opt/render/project/src/media
databases:
  - name: parcial20-db
    databaseName: parcial20
    user: parcial20_user
